---
name: action-pdk-test-unit
description: Runs `pdk test unit` on your code
inputs:
  puppet-version:
    description: A string indicating the Puppet version to validate against, such as "5.4.2" or "5.5".
    required: false
  pe-version:
    description: A string indicating the PE version to validate against, such as "2017.3.5" or "2018.1".
    required: false
  pdk-image:
    description: A string indicating the docker image to build from, such as "puppet/pdk:latest" or "puppet/pdk:nightly".
    required: false
  module-dir:
    description: A string indicating the module location if not workspace root
    required: false        
branding:
  icon: check-square
  color: orange
runs:
  using: docker
  image: Dockerfile
  env:
    PUPPET_VERSION: ${{ inputs.puppet-version }}
    PE_VERSION: ${{ inputs.pe-version }}
    PDKIMAGE: ${{ inputs.pdk-image }}
    MODULE_DIR: ${{ inputs.module-dir }}
